export default {
    SERVER_URL: 'http://192.168.56.1:8088',
    ROUTES: {
      LOGIN: 'login',
      LIKE: 'time/like',
      DEFAULT_CATEGORY: 'time/defaultCat',
      CATEGORY_UPLOAD: 'time/category',
      ALL_POST: 'time/allPost',
      UPLOAD_POST: 'time/timeline',
      FORGET_PASSWORD: 'forget',
      SINGLE_POST: 'time/singlePost',
      COMMENT_SAVE: 'time/saveComment',
      SIGN_UP: 'signup',
      DEFAULT_COMMENTS: 'time/all_Comments',
      CHANGE_PASSWORD: 'changePassword',
      VERIFY: 'verify',
      SHARE: 'share',
      FEATURED_POST: 'time/featured',
      POST_COUNT: 'time/postCount',
    },
    credentials: {
      mailId: '###############',
      password: '########',
    },
  };